#!/usr/bin/env bash
# R-8 component generator with design-token enforcement per §26 v1.11.
#
# Emits a fully-conformed React/Next.js component scaffold consisting of:
#   1. <ComponentName>.tsx           — component module
#   2. <ComponentName>.stories.tsx   — Storybook story
#   3. <ComponentName>.test.tsx      — Vitest unit test
#   4. <ComponentName>.axe.test.tsx  — a11y axe smoke test
#   5. index.ts (appended)           — barrel export
#
# Generated component refuses to reference untokenized raw values
# (hex literals, magic numbers in px/rem). Raw values supplied via
# --default-color or --default-padding must match a token id in
# design-tokens/registry.yaml; otherwise the generator exits 2.
#
# Usage:
#   component-add.sh --name <PascalCase> [--target-dir <dir>]
#                    [--registry <path>] [--default-color <token-id>]
#                    [--default-padding <token-id>] [--dry-run]
set -uo pipefail

NAME=""
TARGET_DIR="src/components"
REGISTRY="design-tokens/registry.yaml"
DEFAULT_COLOR=""
DEFAULT_PADDING=""
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --target-dir) TARGET_DIR="$2"; shift 2 ;;
    --registry) REGISTRY="$2"; shift 2 ;;
    --default-color) DEFAULT_COLOR="$2"; shift 2 ;;
    --default-padding) DEFAULT_PADDING="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help)
      echo "Usage: component-add.sh --name <PascalCase> [--target-dir <dir>] [--registry <path>] [--default-color <token-id>] [--default-padding <token-id>] [--dry-run]" >&2
      exit 0
      ;;
    *) echo "component-add: unknown arg: $1" >&2; exit 2 ;;
  esac
done

[[ -z "$NAME" ]] && { echo "component-add: --name required" >&2; exit 2; }
if ! [[ "$NAME" =~ ^[A-Z][A-Za-z0-9]+$ ]]; then
  echo "component-add: --name must be PascalCase (got: $NAME)" >&2
  exit 2
fi

# Resolve registry path: try as-given first (relative to caller cwd),
# then plugin root, then plugin root with leading slash stripped.
if [[ ! -f "$REGISTRY" ]]; then
  PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd -P)}"
  if [[ -f "$PLUGIN_ROOT/$REGISTRY" ]]; then
    REGISTRY="$PLUGIN_ROOT/$REGISTRY"
  else
    echo "component-add: registry not found: $REGISTRY" >&2
    exit 2
  fi
fi

# Verify any supplied --default-* token id is in the registry and not
# deprecated.
verify_token() {
  local flag="$1" id="$2"
  [[ -z "$id" ]] && return 0
  # Reject hex literals + raw px/rem.
  if [[ "$id" =~ ^# || "$id" =~ ^[0-9]+(px|rem|em)$ ]]; then
    echo "component-add: $flag must be a token id (got raw value: $id); use a token id from $REGISTRY" >&2
    exit 2
  fi
  if ! grep -qE "^  - id: $id\$" "$REGISTRY"; then
    echo "component-add: $flag token id not in registry: $id" >&2
    exit 2
  fi
  local dep
  dep=$(awk -v target="$id" '
      /^  - id: / { in_block = ($0 == "  - id: "target) }
      in_block && /^    deprecated: true/ { print "yes"; exit }
    ' "$REGISTRY")
  if [[ "$dep" == "yes" ]]; then
    echo "component-add: $flag token $id is deprecated; pass replaced_by successor instead" >&2
    exit 2
  fi
  return 0
}
verify_token --default-color "$DEFAULT_COLOR"
verify_token --default-padding "$DEFAULT_PADDING"

COMP_DIR="$TARGET_DIR/$NAME"
COMP_FILE="$COMP_DIR/$NAME.tsx"
STORY_FILE="$COMP_DIR/$NAME.stories.tsx"
TEST_FILE="$COMP_DIR/$NAME.test.tsx"
AXE_FILE="$COMP_DIR/$NAME.axe.test.tsx"
BARREL_FILE="$TARGET_DIR/index.ts"

if [[ -e "$COMP_DIR" && "$DRY_RUN" -ne 1 ]]; then
  echo "component-add: target $COMP_DIR already exists; refuse to overwrite" >&2
  exit 2
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "component-add: dry_run=true would write $COMP_FILE $STORY_FILE $TEST_FILE $AXE_FILE and append to $BARREL_FILE" >&2
  exit 0
fi

mkdir -p "$COMP_DIR"

cat > "$COMP_FILE" <<TSX_EOF
// Generated by R-8 component-add per §26 v1.11.
// Tokens consulted: ${DEFAULT_COLOR:-<none>} ${DEFAULT_PADDING:-<none>}.
import { tokens } from "../../../design-tokens";

export type ${NAME}Props = {
  children?: React.ReactNode;
};

export const $NAME = ({ children }: ${NAME}Props) => {
  return <div data-component="$NAME">{children}</div>;
};
TSX_EOF

cat > "$STORY_FILE" <<TSX_EOF
// Generated Storybook story for $NAME (R-8 §26 v1.11).
import type { Meta, StoryObj } from "@storybook/react";
import { $NAME } from "./$NAME";

const meta: Meta<typeof $NAME> = {
  component: $NAME,
  title: "Generated/$NAME",
};
export default meta;
type Story = StoryObj<typeof $NAME>;
export const Default: Story = { args: { children: "$NAME" } };
TSX_EOF

cat > "$TEST_FILE" <<TSX_EOF
// Generated Vitest unit test for $NAME (R-8 §26 v1.11).
import { describe, it, expect } from "vitest";
import { render } from "@testing-library/react";
import { $NAME } from "./$NAME";

describe("$NAME", () => {
  it("renders with data-component attribute", () => {
    const { container } = render(<$NAME>hello</$NAME>);
    expect(container.querySelector("[data-component=\"$NAME\"]")).not.toBeNull();
  });
});
TSX_EOF

cat > "$AXE_FILE" <<TSX_EOF
// Generated a11y axe smoke test for $NAME (R-8 §26 v1.11; R-3 a11y-axe consumer).
import { describe, it, expect } from "vitest";
import { render } from "@testing-library/react";
import { axe } from "jest-axe";
import { $NAME } from "./$NAME";

describe("$NAME (a11y)", () => {
  it("has no axe violations", async () => {
    const { container } = render(<$NAME>label</$NAME>);
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });
});
TSX_EOF

mkdir -p "$TARGET_DIR"
{
  [[ -f "$BARREL_FILE" ]] && cat "$BARREL_FILE"
  echo "export { $NAME } from \"./$NAME/$NAME\";"
} > "$BARREL_FILE.tmp" && mv "$BARREL_FILE.tmp" "$BARREL_FILE"

echo "component-add: wrote $COMP_FILE $STORY_FILE $TEST_FILE $AXE_FILE" >&2
echo "component-add: appended export to $BARREL_FILE" >&2
exit 0
