#!/usr/bin/env bash
# X-6 IDE rules export per §14. Reads every rule from the
# generated-code-quality-standards/ tree and emits a one-way ESLint-shaped
# configuration that the IDE ecosystem (Cursor, Continue, Aider, Copilot,
# Windsurf) consumes via standard ESLint configuration discovery.
#
# Per §14 X-6: one-way artifact — IDE consumers read but never write back.
# Differs from X-8 (LSP server) which is a live diagnostic channel.
#
# Usage:
#   commands/export-rules.sh --target <path> [--format eslint|biome|stylelint]
#                            [--dry-run]
#
# Exit codes:
#   0 — export written (or dry-run plan emitted)
#   2 — usage error

set -uo pipefail

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd -P)}"

# Per §23 X-6: positional <ide> (cursor|vscode-copilot|continue|aider|
# windsurf) + --profile + --include + --exclude + --out + --skip-fresh +
# --dry-run. Legacy --target / --format kept as test-affordance aliases
# during reconciliation.
IDE=""
PROFILE=""
INCLUDE=""
EXCLUDE=""
OUT=""
TARGET=""
FORMAT="eslint"
SKIP_FRESH=0
DRY_RUN=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) PROFILE="$2"; shift 2 ;;
    --include) INCLUDE="${INCLUDE:+$INCLUDE,}$2"; shift 2 ;;
    --exclude) EXCLUDE="${EXCLUDE:+$EXCLUDE,}$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --target) TARGET="$2"; shift 2 ;;
    --format) FORMAT="$2"; shift 2 ;;
    --skip-fresh) SKIP_FRESH=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help)
      echo "Usage: export-rules.sh <ide> [--profile <name>] [--include <ns>] [--exclude <ns>] [--out <dir>] [--skip-fresh] [--dry-run]"
      echo "       <ide>: cursor | vscode-copilot | continue | aider | windsurf"
      echo "  (legacy: --target <path> --format eslint|biome|stylelint)"
      exit 0 ;;
    cursor|vscode-copilot|continue|aider|windsurf) IDE="$1"; shift ;;
    *) echo "export-rules: unknown arg: $1" >&2; exit 2 ;;
  esac
done

[[ -z "$TARGET" && -z "$OUT" && -z "$IDE" ]] && { echo "export-rules: <ide> (or legacy --target <path>) required" >&2; exit 2; }
# Bridge legacy --target / new --out to a single TARGET variable.
[[ -z "$TARGET" && -n "$OUT" ]] && TARGET="$OUT/.${IDE:-eslint}rules.json"
[[ -z "$TARGET" && -n "$IDE" ]] && TARGET="./.${IDE}rules.json"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "export-rules: dry-run; would write $FORMAT config to $TARGET" >&2
  exit 0
fi

mkdir -p "$(dirname "$TARGET")"

case "$FORMAT" in
  eslint)
    # Use the per-source-file ESLint compliance emitter so the resulting
    # config carries the same severity/options the runtime gate applies.
    # Env vars must precede `node` so they reach process.env (positional
    # args after `node -e '...'` are NOT env vars). Bash-3.2 portability
    # gotcha #4.
    PLUGIN_ROOT="$PLUGIN_ROOT" TARGET="$TARGET" node -e '
      const fs = require("fs");
      const path = require("path");
      const root = process.env.PLUGIN_ROOT;
      const target = process.env.TARGET;
      const allRules = {};
      function walk(d) {
        if (!fs.existsSync(d)) return;
        for (const e of fs.readdirSync(d)) {
          if (e === "_meta" || e === "_archived") continue;
          const p = path.join(d, e);
          const st = fs.statSync(p);
          if (st.isDirectory()) walk(p);
          else if (e.endsWith(".yaml")) {
            try {
              const c = fs.readFileSync(p, "utf8");
              const ruleRe = /^\s*-\s*id:\s*([a-zA-Z0-9_/-]+)/gm;
              let m;
              while ((m = ruleRe.exec(c)) !== null) {
                allRules[m[1]] = "warn";
              }
            } catch {}
          }
        }
      }
      walk(path.join(root, "generated-code-quality-standards"));
      const cfg = {
        "//": "X-6 IDE rules export — one-way artifact generated by commands/export-rules.sh; do not edit by hand. Source of truth: generated-code-quality-standards/ tree.",
        rules: allRules
      };
      fs.writeFileSync(target, JSON.stringify(cfg, null, 2) + "\n");
    '
    n=$(grep -c '"g-' "$TARGET" 2>/dev/null || echo 0)
    echo "export-rules: wrote $n rules to $TARGET (format=$FORMAT)" >&2
    ;;
  biome|stylelint)
    # Stub: emit a minimal config carrying the rule ID list. Operators
    # adapt per linter-specific rule plug-in mapping.
    TARGET="$TARGET" node -e '
      const fs = require("fs");
      const target = process.env.TARGET;
      fs.writeFileSync(target, JSON.stringify({
        "//": "X-6 export — '"$FORMAT"' stub. Rule mapping happens in the consumer.",
        rules: {}
      }, null, 2) + "\n");
    '
    echo "export-rules: wrote stub $FORMAT config to $TARGET" >&2
    ;;
  *) echo "export-rules: unknown format: $FORMAT" >&2; exit 2 ;;
esac
exit 0
