#!/usr/bin/env bash
# X-6 IDE rules export per §14. Reads every rule from the
# generated-code-quality-standards/ tree and emits a one-way ESLint-shaped
# configuration that the IDE ecosystem (Cursor, Continue, Aider, Copilot,
# Windsurf) consumes via standard ESLint configuration discovery.
#
# Per §14 X-6: one-way artifact — IDE consumers read but never write back.
# Differs from X-8 (LSP server) which is a live diagnostic channel.
#
# Usage:
#   commands/export-rules.sh --target <path> [--format eslint|biome|stylelint]
#                            [--dry-run]
#
# Exit codes:
#   0 — export written (or dry-run plan emitted)
#   2 — usage error

set -uo pipefail

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd -P)}"

TARGET=""
FORMAT="eslint"
DRY_RUN=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TARGET="$2"; shift 2 ;;
    --format) FORMAT="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help)
      echo "Usage: export-rules.sh --target <path> [--format eslint|biome|stylelint] [--dry-run]"
      exit 0 ;;
    *) echo "export-rules: unknown flag: $1" >&2; exit 2 ;;
  esac
done

[[ -z "$TARGET" ]] && { echo "export-rules: --target <path> required" >&2; exit 2; }

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "export-rules: dry-run; would write $FORMAT config to $TARGET" >&2
  exit 0
fi

mkdir -p "$(dirname "$TARGET")"

case "$FORMAT" in
  eslint)
    # Use the per-source-file ESLint compliance emitter so the resulting
    # config carries the same severity/options the runtime gate applies.
    node -e '
      const fs = require("fs");
      const path = require("path");
      const root = process.env.PLUGIN_ROOT;
      const target = process.env.TARGET;
      const allRules = {};
      function walk(d) {
        if (!fs.existsSync(d)) return;
        for (const e of fs.readdirSync(d)) {
          if (e === "_meta" || e === "_archived") continue;
          const p = path.join(d, e);
          const st = fs.statSync(p);
          if (st.isDirectory()) walk(p);
          else if (e.endsWith(".yaml")) {
            try {
              const c = fs.readFileSync(p, "utf8");
              const ruleRe = /^\s*-\s*id:\s*([a-zA-Z0-9_/-]+)/gm;
              let m;
              while ((m = ruleRe.exec(c)) !== null) {
                allRules[m[1]] = "warn";
              }
            } catch {}
          }
        }
      }
      walk(path.join(root, "generated-code-quality-standards"));
      const cfg = {
        "//": "X-6 IDE rules export — one-way artifact generated by commands/export-rules.sh; do not edit by hand. Source of truth: generated-code-quality-standards/ tree.",
        rules: allRules
      };
      fs.writeFileSync(target, JSON.stringify(cfg, null, 2) + "\n");
    ' PLUGIN_ROOT="$PLUGIN_ROOT" TARGET="$TARGET"
    n=$(grep -c '"g-' "$TARGET" 2>/dev/null || echo 0)
    echo "export-rules: wrote $n rules to $TARGET (format=$FORMAT)" >&2
    ;;
  biome|stylelint)
    # Stub: emit a minimal config carrying the rule ID list. Operators
    # adapt per linter-specific rule plug-in mapping.
    node -e '
      const fs = require("fs");
      const target = process.env.TARGET;
      fs.writeFileSync(target, JSON.stringify({
        "//": "X-6 export — '"$FORMAT"' stub. Rule mapping happens in the consumer.",
        rules: {}
      }, null, 2) + "\n");
    ' TARGET="$TARGET"
    echo "export-rules: wrote stub $FORMAT config to $TARGET" >&2
    ;;
  *) echo "export-rules: unknown format: $FORMAT" >&2; exit 2 ;;
esac
exit 0
