#!/usr/bin/env bash
# /postmortem — F-1 entry point per §16:
#   "skill reproduces as failing test → asks what should have caught it →
#    generates eval spec → optionally drafts rule + detector → queries SIRL/
#    Compliance/L for matches → appends to FAILURE-LOG.md."
#
# This substrate covers the script-shaped pieces of the F-1 flow. The
# conversational reproduction-and-question phase is handled by the
# operator-facing skill (skills/postmortem/SKILL.md, separate CL); this
# script does the deterministic parts the skill orchestrates: emit-test,
# interactive answer capture + eval-spec generation, draft-rule/detector
# scaffolding, SIRL/Compliance keyword matching, FAILURE-LOG append.
#
# Usage:
#   postmortem.sh <bug-description> [--emit-test] [--interactive]
#                  [--draft-rule] [--draft-detector] [--show-historical]
#
# Exit codes (per §2.2 detector contract):
#   0 — success (or historical listing emitted)
#   2 — usage / missing argument

set -uo pipefail

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd -P)}"
BUG_DESCRIPTION=""
EMIT_TEST=0
INTERACTIVE=0
DRAFT_RULE=0
DRAFT_DETECTOR=0
SHOW_HISTORICAL=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --emit-test) EMIT_TEST=1; shift ;;
    --interactive) INTERACTIVE=1; shift ;;
    --draft-rule) DRAFT_RULE=1; shift ;;
    --draft-detector) DRAFT_DETECTOR=1; shift ;;
    --show-historical) SHOW_HISTORICAL=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -*) echo "postmortem: unknown flag: $1" >&2; exit 2 ;;
    *) [[ -z "$BUG_DESCRIPTION" ]] && BUG_DESCRIPTION="$1" || BUG_DESCRIPTION="$BUG_DESCRIPTION $1"; shift ;;
  esac
done

# §2.14 dry-run: short-circuit before any filesystem writes (tests,
# rule drafts, detector stubs).
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "postmortem: dry-run; would draft postmortem for: $BUG_DESCRIPTION (emit-test=$EMIT_TEST)" >&2
  exit 0
fi

if [[ "$SHOW_HISTORICAL" -eq 1 ]]; then
  POSTMORTEMS_DIR="$PLUGIN_ROOT/seed/postmortems"
  if [[ ! -d "$POSTMORTEMS_DIR" ]]; then
    echo "postmortem: no historical postmortems directory at $POSTMORTEMS_DIR" >&2
    exit 1
  fi
  count=$(find "$POSTMORTEMS_DIR" -name '*.jsonl' -type f | wc -l | tr -d ' ')
  echo "$count historical postmortems available" >&2
  exit 0
fi

[[ -z "$BUG_DESCRIPTION" ]] && { echo "postmortem: <bug-description> argument required" >&2; exit 2; }

# Echo the bug description so callers can confirm acceptance (spec 1).
echo "postmortem: bug=\"$BUG_DESCRIPTION\"" >&2

# ts/slug used by all artifact filenames; deterministic per-second to
# avoid collisions in tight loops.
TS=$(date +%Y%m%d-%H%M%S)
SLUG=$(echo "$BUG_DESCRIPTION" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-' | head -c 40)
[[ -z "$SLUG" ]] && SLUG="bug"

# --emit-test: write a Vitest skeleton that reproduces the bug as a
# failing test (red-state by design, per Huntley failure-driven loop).
if [[ "$EMIT_TEST" -eq 1 ]]; then
  mkdir -p tests
  TEST_FILE="tests/postmortem-${TS}-${SLUG}.test.ts"
  cat > "$TEST_FILE" <<TS_EOF
// Reproduces: ${BUG_DESCRIPTION}
// Generated by /postmortem (F-1) at ${TS}.
// Initially red — fails to surface the bug; turns green when fix lands.
import { describe, it, expect } from "vitest";

describe("postmortem: ${BUG_DESCRIPTION}", () => {
  it("should not exhibit the reported defect", () => {
    expect(false).toBe(true); // TODO: replace with reproducer assertion
  });
});
TS_EOF
  echo "postmortem: wrote $TEST_FILE" >&2
fi

# --interactive: ask "what hook/rubric rule should have caught this?",
# read the operator's answer (rule-id or free text) from stdin, and
# generate a §2.4 eval spec under evals/specs/postmortem-*.json with
# a rationale derived from the bug description and answer.
if [[ "$INTERACTIVE" -eq 1 ]]; then
  echo "what hook/rubric rule should have caught this?" >&2
  read -r CAUGHT_BY || CAUGHT_BY="unknown"
  CAUGHT_BY="${CAUGHT_BY:-unknown}"
  mkdir -p evals/specs
  SPEC_FILE="evals/specs/postmortem-${TS}-${SLUG}.json"
  RATIONALE="bug \"${BUG_DESCRIPTION}\" was not caught by ${CAUGHT_BY}; this spec asserts the missing detection so future regressions surface immediately"
  CAUGHT_BY="$CAUGHT_BY" RATIONALE="$RATIONALE" BUG="$BUG_DESCRIPTION" SPEC_FILE="$SPEC_FILE" node -e '
    const fs = require("fs");
    fs.writeFileSync(process.env.SPEC_FILE, JSON.stringify({
      name: `postmortem: ${process.env.BUG}`,
      category: "operational",
      subject: process.env.CAUGHT_BY,
      command: "echo postmortem-stub",
      setup: [],
      expect: { exit_code: 0 },
      rationale: process.env.RATIONALE
    }, null, 2) + "\n");
  '
  echo "postmortem: wrote $SPEC_FILE caught_by=$CAUGHT_BY" >&2
fi

# --draft-rule: scaffold a rubric rule YAML at rubric/_draft/new-rule.yaml.
# Operator promotes from _draft/ into a real source folder after curation.
if [[ "$DRAFT_RULE" -eq 1 ]]; then
  mkdir -p rubric/_draft
  cat > rubric/_draft/new-rule.yaml <<RULE_EOF
# Drafted by /postmortem (F-1) for: ${BUG_DESCRIPTION}
id: drafted-from-postmortem
name: drafted-from-postmortem
description: "${BUG_DESCRIPTION}"
detector: rubric/detectors/_draft/drafted-from-postmortem.sh
type: problem
fixable: null
RULE_EOF
  echo "postmortem: wrote rubric/_draft/new-rule.yaml" >&2
fi

# --draft-detector: scaffold a detector script at rubric/detectors/_draft/.
if [[ "$DRAFT_DETECTOR" -eq 1 ]]; then
  mkdir -p rubric/detectors/_draft
  DETECTOR_FILE="rubric/detectors/_draft/postmortem-${TS}-${SLUG}.sh"
  cat > "$DETECTOR_FILE" <<DETECT_EOF
#!/usr/bin/env bash
# Drafted by /postmortem (F-1) for: ${BUG_DESCRIPTION}
# Per §2.2 detector contract: exit 0 = clean, 2 = violation, 1 = error.
set -uo pipefail
echo "TODO: implement detector for: ${BUG_DESCRIPTION}" >&2
exit 0
DETECT_EOF
  chmod +x "$DETECTOR_FILE"
  echo "postmortem: wrote $DETECTOR_FILE" >&2
fi

# Standards-layer (S-6 SIRL) keyword match: if the bug description hints
# at a known standards domain, surface the candidate source-namespace so
# the operator can drill into S-6 provenance for that namespace.
SIRL_HITS=""
case "$BUG_DESCRIPTION" in
  *"schema validation"*|*"input validation"*|*"injection"*|*"XSS"*)
    SIRL_HITS="$SIRL_HITS owasp-asvs" ;;
esac
case "$BUG_DESCRIPTION" in
  *"react"*|*"hook"*|*"component"*) SIRL_HITS="$SIRL_HITS google-react" ;;
esac
case "$BUG_DESCRIPTION" in
  *"crypto"*|*"key management"*|*"encryption"*) SIRL_HITS="$SIRL_HITS owasp-asvs" ;;
esac
[[ -n "$SIRL_HITS" ]] && echo "postmortem: standards-layer matches:$SIRL_HITS" >&2

# Compliance-layer keyword match: if the bug description aligns with a
# control area, surface the candidate framework.
COMPLIANCE_HITS=""
case "$BUG_DESCRIPTION" in
  *"audit log"*|*"audit trail"*|*"access log"*) COMPLIANCE_HITS="$COMPLIANCE_HITS soc2-tsc" ;;
esac
case "$BUG_DESCRIPTION" in
  *"PII"*|*"GDPR"*|*"data export"*) COMPLIANCE_HITS="$COMPLIANCE_HITS gdpr" ;;
esac
case "$BUG_DESCRIPTION" in
  *"PCI"*|*"card"*|*"payment"*) COMPLIANCE_HITS="$COMPLIANCE_HITS pci-dss" ;;
esac
[[ -n "$COMPLIANCE_HITS" ]] && echo "postmortem: compliance-layer matches:$COMPLIANCE_HITS" >&2

# Append dated entry to FAILURE-LOG.md per Huntley failure-domain log.
DATE_HEADING=$(date +%Y-%m-%d)
[[ ! -f FAILURE-LOG.md ]] && touch FAILURE-LOG.md
{
  echo ""
  echo "### ${DATE_HEADING} — ${BUG_DESCRIPTION}"
  echo ""
  echo "- Reported via /postmortem"
  [[ -n "$SIRL_HITS" ]] && echo "- Standards matches:$SIRL_HITS"
  [[ -n "$COMPLIANCE_HITS" ]] && echo "- Compliance matches:$COMPLIANCE_HITS"
} >> FAILURE-LOG.md

exit 0
