#!/usr/bin/env bash
# W-9 ui-regression-pinner emitter. Writes a Playwright DOM spec to
# tests/e2e/<feature-id>.spec.ts pinning click-state, navigation,
# rendered-output, and accessible-name per WCAG-2.2.
set -uo pipefail
ROOT=""; FEATURE_ID=""; TESTS_OUT=""; DIFF_STUB=""; EMIT=""; ACTIVE_SUITE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="$2"; shift 2 ;;
    --feature-id) FEATURE_ID="$2"; shift 2 ;;
    --tests-out) TESTS_OUT="$2"; shift 2 ;;
    --diff-stub) DIFF_STUB="$2"; shift 2 ;;
    --emit) EMIT="$2"; shift 2 ;;
    --active-suite) ACTIVE_SUITE="$2"; shift 2 ;;
    -h|--help) echo "Usage: ui-regression-pinner.sh --root <repo> --feature-id <id> --tests-out <dir> --diff-stub touched=<path> [--emit assertions] [--active-suite <dir>]"; exit 0 ;;
    *) shift ;;
  esac
done
[[ -z "$FEATURE_ID" || -z "$TESTS_OUT" ]] && { echo "ui-regression-pinner: --feature-id and --tests-out required" >&2; exit 2; }

# Duplicate-coverage check: refuse to emit when active suite already covers it.
if [[ -n "$ACTIVE_SUITE" && -d "$ACTIVE_SUITE" ]]; then
  if find "$ACTIVE_SUITE" -name "$FEATURE_ID.spec.ts" -type f 2>/dev/null | grep -q .; then
    echo "ui-regression-pinner: duplicate_coverage feature_id=$FEATURE_ID (active suite already covers rendered behavior)" >&2
    exit 2
  fi
fi

# Emit assertions list (no test write).
if [[ "$EMIT" == "assertions" ]]; then
  echo "ui-regression-pinner: assertion=accessible-name (WCAG-2.2 4.1.2)" >&2
  echo "ui-regression-pinner: assertion=click-state (mounted button state after click)" >&2
  echo "ui-regression-pinner: assertion=rendered-output (visible text)" >&2
  echo "ui-regression-pinner: assertion=navigation (route after click)" >&2
  exit 0
fi

mkdir -p "$TESTS_OUT"
TEST_FILE="$TESTS_OUT/$FEATURE_ID.spec.ts"
cat > "$TEST_FILE" <<EOF
// Generated by ui-regression-pinner for feature $FEATURE_ID.
// Pins click-state, navigation, rendered output, and accessible-name
// per WCAG-2.2 standard.
import { test, expect } from "@playwright/test";

test("$FEATURE_ID — accessible name + rendered output", async ({ page }) => {
  await page.goto("/");
  const button = page.getByRole("button", { name: /submit|continue|save/i });
  await expect(button).toBeVisible();
  await expect(button).toHaveAccessibleName(/.+/);
});

test("$FEATURE_ID — click state + navigation", async ({ page }) => {
  await page.goto("/");
  const button = page.getByRole("button").first();
  await button.click();
  await expect(page).toHaveURL(/.+/);
});
EOF
echo "ui-regression-pinner: wrote $TEST_FILE feature_id=$FEATURE_ID" >&2
