#!/usr/bin/env bash
# standards/registry-domains.sh — derive the egress allowlist from every URL registry.
#
# Walks every registry surface that can name a rules-source URL (standards/*sources*.yaml,
# standards/technology-*-registry.yaml, .claude-tdd-pro/*URLS*.yaml, pr-corpus/*SOURCES*.yaml,
# pr-corpus/*sources*.yaml — globbed, so a registry file added later is swept automatically),
# extracts every http(s) URL, and emits the sorted unique set of domains. Adding a URL to any
# registry therefore adds its domain here with NO manual list maintenance.
#
# Why: restricted cloud sessions can only reach hosts on their environment's network
# allowlist — a security boundary only the operator can change. This script makes the
# complete, current allowlist a one-command artifact (standards/EGRESS-ALLOWLIST.txt,
# committed) that the operator pastes into the environment settings once and re-syncs when
# the drift gate says so. Desktops and the GitHub Actions scrape plane (§33 CL-564.j) have
# open egress and need nothing.
#
# CLI:
#   registry-domains.sh [--root <plugin-root>] [--out <file>] [--check]
#     --root   plugin root to scan (default: CLAUDE_PLUGIN_ROOT or script's parent)
#     --out    write the allowlist file (default: <root>/standards/EGRESS-ALLOWLIST.txt)
#     --check  drift gate: regenerate and compare against the committed file;
#              exit 1 with a diff when a registry URL's domain is missing/stale
# stdout: one domain per line (the generated body, without the header)
# stderr: `registry-domains root=<root> registries=<n> domains=<n> [drift=none|DRIFT]`
# Exit: 0 ok / in sync | 1 drift (--check) | 2 usage

set -uo pipefail

ROOT=""; OUT=""; CHECK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --root)  ROOT="${2-}";  shift 2 ;;
    --out)   OUT="${2-}";   shift 2 ;;
    --check) CHECK=1;       shift   ;;
    -h|--help) sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//' >&2; exit 0 ;;
    *) echo "registry-domains: unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -z "$ROOT" ] && ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd -P)}"
[ -d "$ROOT" ] || { echo "registry-domains: not a directory: $ROOT" >&2; exit 2; }
[ -z "$OUT" ] && OUT="$ROOT/standards/EGRESS-ALLOWLIST.txt"

REGS=()
for g in "$ROOT"/standards/*sources*.yaml "$ROOT"/standards/technology-*-registry.yaml \
         "$ROOT"/.claude-tdd-pro/*URLS*.yaml "$ROOT"/pr-corpus/*SOURCES*.yaml \
         "$ROOT"/pr-corpus/*sources*.yaml; do
  [ -f "$g" ] && REGS+=("$g")
done
[ ${#REGS[@]} -gt 0 ] || { echo "registry-domains: no registry files under $ROOT" >&2; exit 2; }

BODY=$(grep -rhoE "https?://[^\"' ]+" "${REGS[@]+"${REGS[@]}"}" 2>/dev/null | python3 -c '
import sys, urllib.parse
hosts = set()
for line in sys.stdin:
    u = line.strip().rstrip(",);")
    if not u: continue
    h = urllib.parse.urlparse(u).netloc.lower()
    if h: hosts.add(h)
print("\n".join(sorted(hosts)))
')

HEADER="# EGRESS-ALLOWLIST.txt — generated by standards/registry-domains.sh; do not edit by hand.
# Every domain referenced by a rules-source URL registry in this plugin, one per line.
# Restricted cloud sessions: paste these into the environment network allowlist so
# scraping works there the way it works on desktop. Re-sync when --check reports drift."

if [ "$CHECK" -eq 1 ]; then
  TMP=$(mktemp)
  printf '%s\n%s\n' "$HEADER" "$BODY" > "$TMP"
  if [ ! -f "$OUT" ] || ! diff -u "$OUT" "$TMP" >&2; then
    rm -f "$TMP"
    echo "registry-domains root=$ROOT registries=${#REGS[@]} domains=$(printf '%s\n' "$BODY" | grep -c .) drift=DRIFT — regenerate: bash standards/registry-domains.sh" >&2
    exit 1
  fi
  rm -f "$TMP"
  printf '%s\n' "$BODY"
  echo "registry-domains root=$ROOT registries=${#REGS[@]} domains=$(printf '%s\n' "$BODY" | grep -c .) drift=none" >&2
  exit 0
fi

printf '%s\n%s\n' "$HEADER" "$BODY" > "$OUT"
printf '%s\n' "$BODY"
echo "registry-domains root=$ROOT registries=${#REGS[@]} domains=$(printf '%s\n' "$BODY" | grep -c .) wrote=$OUT" >&2
